services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:17
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  pgdata:
