# Generated by Django 5.2.5 on 2025-08-10 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subpost",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="subpost",
            name="views",
        ),
    ]
