# Generated by Django 5.2.5 on 2025-08-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_subpost_likes_remove_subpost_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="views",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
