# Generated by Django 5.2.5 on 2025-08-10 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_post_likes_alter_post_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subpost",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subposts",
                to="api.post",
            ),
        ),
    ]
