# Generated by Django 5.2.5 on 2025-08-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_view"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="views",
            new_name="views_count",
        ),
    ]
