# Generated by Django 5.2.5 on 2025-08-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_views_post_views_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="views_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
